-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity create_tree is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_value_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in_value_V_ce0 : OUT STD_LOGIC;
    in_value_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_frequency_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    in_frequency_V_ce0 : OUT STD_LOGIC;
    in_frequency_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    val_assign_loc_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    val_assign_loc_empty_n : IN STD_LOGIC;
    val_assign_loc_read : OUT STD_LOGIC;
    parent_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    parent_V_ce0 : OUT STD_LOGIC;
    parent_V_we0 : OUT STD_LOGIC;
    parent_V_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    left_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    left_V_ce0 : OUT STD_LOGIC;
    left_V_we0 : OUT STD_LOGIC;
    left_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    right_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    right_V_ce0 : OUT STD_LOGIC;
    right_V_we0 : OUT STD_LOGIC;
    right_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    val_assign_loc_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    val_assign_loc_out_full_n : IN STD_LOGIC;
    val_assign_loc_out_write : OUT STD_LOGIC );
end;


architecture behav of create_tree is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal val_assign_loc_blk_n : STD_LOGIC;
    signal val_assign_loc_out_blk_n : STD_LOGIC;
    signal val_assign_loc_read_reg_477 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal add_ln15_fu_327_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln15_reg_483 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_333_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_reg_488 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln15_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_reg_496 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_342_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal i_reg_500 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln544_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_reg_505 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln887_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal frequency_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln879_2_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_1_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_1_reg_547 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln544_5_fu_409_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_5_reg_551 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln879_4_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_4_reg_571 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal and_ln42_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln42_reg_575 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln44_fu_436_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln44_reg_579 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln209_fu_441_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln209_reg_584 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln49_fu_447_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln49_reg_589 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln209_1_fu_452_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln209_1_reg_594 : STD_LOGIC_VECTOR (31 downto 0);
    signal frequency_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal frequency_V_ce0 : STD_LOGIC;
    signal frequency_V_we0 : STD_LOGIC;
    signal frequency_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_V_3_reg_229 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_p_0168_2_i_i_phi_fu_301_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal t_V_reg_241 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_p_094_2_i_i_phi_fu_313_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_assign_reg_253 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_t_V_5_phi_fu_269_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_V_5_reg_266 : STD_LOGIC_VECTOR (31 downto 0);
    signal tree_count_V_fu_397_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_count_V_fu_385_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_t_V_4_phi_fu_280_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_V_4_reg_277 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_090_0_i_i_reg_288 : STD_LOGIC_VECTOR (31 downto 0);
    signal tree_count_V_1_fu_465_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_count_V_1_fu_458_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln544_3_fu_353_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln28_fu_380_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln33_fu_392_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_6_fu_414_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln544_4_fu_472_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_3_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_condition_222 : BOOLEAN;
    signal ap_condition_229 : BOOLEAN;
    signal ap_condition_201 : BOOLEAN;
    signal ap_condition_208 : BOOLEAN;
    signal ap_condition_156 : BOOLEAN;
    signal ap_condition_166 : BOOLEAN;

    component create_tree_frequhbi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    frequency_V_U : component create_tree_frequhbi
    generic map (
        DataWidth => 32,
        AddressRange => 255,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => frequency_V_address0,
        ce0 => frequency_V_ce0,
        we0 => frequency_V_we0,
        d0 => frequency_V_d0,
        q0 => frequency_V_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    op2_assign_reg_253_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_496 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                op2_assign_reg_253 <= i_reg_500;
            elsif ((not(((val_assign_loc_out_full_n = ap_const_logic_0) or (val_assign_loc_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                op2_assign_reg_253 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    p_090_0_i_i_reg_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                if ((ap_const_boolean_1 = ap_condition_208)) then 
                    p_090_0_i_i_reg_288 <= frequency_V_q0;
                elsif ((ap_const_boolean_1 = ap_condition_201)) then 
                    p_090_0_i_i_reg_288 <= in_frequency_V_q0;
                end if;
            end if; 
        end if;
    end process;

    t_V_3_reg_229_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_496 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                t_V_3_reg_229 <= ap_phi_mux_p_0168_2_i_i_phi_fu_301_p4;
            elsif ((not(((val_assign_loc_out_full_n = ap_const_logic_0) or (val_assign_loc_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_V_3_reg_229 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    t_V_4_reg_277_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                if ((ap_const_boolean_1 = ap_condition_208)) then 
                    t_V_4_reg_277 <= t_V_reg_241;
                elsif ((ap_const_boolean_1 = ap_condition_201)) then 
                    t_V_4_reg_277 <= in_count_V_fu_385_p2;
                end if;
            end if; 
        end if;
    end process;

    t_V_5_reg_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                if ((ap_const_boolean_1 = ap_condition_208)) then 
                    t_V_5_reg_266 <= tree_count_V_fu_397_p2;
                elsif ((ap_const_boolean_1 = ap_condition_201)) then 
                    t_V_5_reg_266 <= t_V_3_reg_229;
                end if;
            end if; 
        end if;
    end process;

    t_V_reg_241_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_496 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                t_V_reg_241 <= ap_phi_mux_p_094_2_i_i_phi_fu_313_p4;
            elsif ((not(((val_assign_loc_out_full_n = ap_const_logic_0) or (val_assign_loc_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_V_reg_241 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((val_assign_loc_out_full_n = ap_const_logic_0) or (val_assign_loc_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                add_ln15_reg_483 <= add_ln15_fu_327_p2;
                val_assign_loc_read_reg_477 <= val_assign_loc_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (((ap_const_lv1_1 = and_ln42_fu_430_p2) and (icmp_ln887_1_reg_547 = ap_const_lv1_1)) or ((icmp_ln879_4_fu_420_p2 = ap_const_lv1_0) and (icmp_ln887_1_reg_547 = ap_const_lv1_0))))) then
                add_ln209_1_reg_594 <= add_ln209_1_fu_452_p2;
                    zext_ln49_reg_589(30 downto 0) <= zext_ln49_fu_447_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (((icmp_ln887_1_reg_547 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln42_fu_430_p2)) or ((icmp_ln879_4_fu_420_p2 = ap_const_lv1_1) and (icmp_ln887_1_reg_547 = ap_const_lv1_0))))) then
                add_ln209_reg_584 <= add_ln209_fu_441_p2;
                    zext_ln44_reg_579(30 downto 0) <= zext_ln44_fu_436_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln887_1_reg_547 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                and_ln42_reg_575 <= and_ln42_fu_430_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_500 <= i_fu_342_p2;
                icmp_ln15_reg_496 <= icmp_ln15_fu_337_p2;
                    zext_ln15_reg_488(30 downto 0) <= zext_ln15_fu_333_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln887_1_reg_547 = ap_const_lv1_0))) then
                icmp_ln879_4_reg_571 <= icmp_ln879_4_fu_420_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                icmp_ln887_1_reg_547 <= icmp_ln887_1_fu_404_p2;
                    zext_ln544_5_reg_551(31 downto 0) <= zext_ln544_5_fu_409_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_fu_337_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    zext_ln544_reg_505(31 downto 0) <= zext_ln544_fu_348_p1(31 downto 0);
            end if;
        end if;
    end process;
    zext_ln15_reg_488(31) <= '0';
    zext_ln544_reg_505(63 downto 32) <= "00000000000000000000000000000000";
    zext_ln544_5_reg_551(63 downto 32) <= "00000000000000000000000000000000";
    zext_ln44_reg_579(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln49_reg_589(63 downto 31) <= "000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, val_assign_loc_empty_n, val_assign_loc_out_full_n, ap_CS_fsm_state2, icmp_ln15_fu_337_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((val_assign_loc_out_full_n = ap_const_logic_0) or (val_assign_loc_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln15_fu_337_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln15_fu_327_p2 <= std_logic_vector(unsigned(val_assign_loc_dout) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln209_1_fu_452_p2 <= std_logic_vector(unsigned(frequency_V_q0) + unsigned(p_090_0_i_i_reg_288));
    add_ln209_fu_441_p2 <= std_logic_vector(unsigned(in_frequency_V_q0) + unsigned(p_090_0_i_i_reg_288));
    and_ln26_fu_374_p2 <= (icmp_ln879_fu_369_p2 and grp_fu_321_p2);
    and_ln42_fu_430_p2 <= (icmp_ln879_3_fu_425_p2 and grp_fu_321_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, val_assign_loc_empty_n, val_assign_loc_out_full_n)
    begin
                ap_block_state1 <= ((val_assign_loc_out_full_n = ap_const_logic_0) or (val_assign_loc_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_condition_156_assign_proc : process(icmp_ln887_1_reg_547, icmp_ln879_4_fu_420_p2, and_ln42_fu_430_p2)
    begin
                ap_condition_156 <= (((icmp_ln887_1_reg_547 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln42_fu_430_p2)) or ((icmp_ln879_4_fu_420_p2 = ap_const_lv1_1) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)));
    end process;


    ap_condition_166_assign_proc : process(icmp_ln887_1_reg_547, icmp_ln879_4_fu_420_p2, and_ln42_fu_430_p2)
    begin
                ap_condition_166 <= (((ap_const_lv1_1 = and_ln42_fu_430_p2) and (icmp_ln887_1_reg_547 = ap_const_lv1_1)) or ((icmp_ln879_4_fu_420_p2 = ap_const_lv1_0) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)));
    end process;


    ap_condition_201_assign_proc : process(icmp_ln887_fu_359_p2, icmp_ln879_2_fu_364_p2, and_ln26_fu_374_p2)
    begin
                ap_condition_201 <= (((icmp_ln887_fu_359_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln26_fu_374_p2)) or ((icmp_ln879_2_fu_364_p2 = ap_const_lv1_1) and (icmp_ln887_fu_359_p2 = ap_const_lv1_0)));
    end process;


    ap_condition_208_assign_proc : process(icmp_ln887_fu_359_p2, icmp_ln879_2_fu_364_p2, and_ln26_fu_374_p2)
    begin
                ap_condition_208 <= (((ap_const_lv1_1 = and_ln26_fu_374_p2) and (icmp_ln887_fu_359_p2 = ap_const_lv1_1)) or ((icmp_ln879_2_fu_364_p2 = ap_const_lv1_0) and (icmp_ln887_fu_359_p2 = ap_const_lv1_0)));
    end process;


    ap_condition_222_assign_proc : process(icmp_ln15_reg_496, icmp_ln887_1_reg_547, icmp_ln879_4_reg_571, and_ln42_reg_575)
    begin
                ap_condition_222 <= (((icmp_ln887_1_reg_547 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln42_reg_575)) or ((icmp_ln879_4_reg_571 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)));
    end process;


    ap_condition_229_assign_proc : process(icmp_ln15_reg_496, icmp_ln887_1_reg_547, icmp_ln879_4_reg_571, and_ln42_reg_575)
    begin
                ap_condition_229 <= (((ap_const_lv1_1 = and_ln42_reg_575) and (icmp_ln887_1_reg_547 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1)) or ((icmp_ln15_reg_496 = ap_const_lv1_1) and (icmp_ln879_4_reg_571 = ap_const_lv1_0) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_p_0168_2_i_i_phi_fu_301_p4_assign_proc : process(ap_CS_fsm_state5, t_V_5_reg_266, tree_count_V_1_fu_465_p2, ap_condition_222, ap_condition_229)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
            if ((ap_const_boolean_1 = ap_condition_229)) then 
                ap_phi_mux_p_0168_2_i_i_phi_fu_301_p4 <= tree_count_V_1_fu_465_p2;
            elsif ((ap_const_boolean_1 = ap_condition_222)) then 
                ap_phi_mux_p_0168_2_i_i_phi_fu_301_p4 <= t_V_5_reg_266;
            else 
                ap_phi_mux_p_0168_2_i_i_phi_fu_301_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_p_0168_2_i_i_phi_fu_301_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_p_094_2_i_i_phi_fu_313_p4_assign_proc : process(ap_CS_fsm_state5, t_V_4_reg_277, in_count_V_1_fu_458_p2, ap_condition_222, ap_condition_229)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
            if ((ap_const_boolean_1 = ap_condition_229)) then 
                ap_phi_mux_p_094_2_i_i_phi_fu_313_p4 <= t_V_4_reg_277;
            elsif ((ap_const_boolean_1 = ap_condition_222)) then 
                ap_phi_mux_p_094_2_i_i_phi_fu_313_p4 <= in_count_V_1_fu_458_p2;
            else 
                ap_phi_mux_p_094_2_i_i_phi_fu_313_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_p_094_2_i_i_phi_fu_313_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_t_V_4_phi_fu_280_p4_assign_proc : process(ap_CS_fsm_state3, t_V_reg_241, in_count_V_fu_385_p2, ap_condition_201, ap_condition_208)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((ap_const_boolean_1 = ap_condition_208)) then 
                ap_phi_mux_t_V_4_phi_fu_280_p4 <= t_V_reg_241;
            elsif ((ap_const_boolean_1 = ap_condition_201)) then 
                ap_phi_mux_t_V_4_phi_fu_280_p4 <= in_count_V_fu_385_p2;
            else 
                ap_phi_mux_t_V_4_phi_fu_280_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_t_V_4_phi_fu_280_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_t_V_5_phi_fu_269_p4_assign_proc : process(ap_CS_fsm_state3, t_V_3_reg_229, tree_count_V_fu_397_p2, ap_condition_201, ap_condition_208)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((ap_const_boolean_1 = ap_condition_208)) then 
                ap_phi_mux_t_V_5_phi_fu_269_p4 <= tree_count_V_fu_397_p2;
            elsif ((ap_const_boolean_1 = ap_condition_201)) then 
                ap_phi_mux_t_V_5_phi_fu_269_p4 <= t_V_3_reg_229;
            else 
                ap_phi_mux_t_V_5_phi_fu_269_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_t_V_5_phi_fu_269_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    frequency_V_address0_assign_proc : process(ap_CS_fsm_state2, icmp_ln15_reg_496, zext_ln544_fu_348_p1, ap_CS_fsm_state3, icmp_ln887_1_reg_547, zext_ln544_5_fu_409_p1, icmp_ln879_4_reg_571, and_ln42_reg_575, zext_ln44_reg_579, zext_ln49_reg_589, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (((ap_const_lv1_1 = and_ln42_reg_575) and (icmp_ln887_1_reg_547 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1)) or ((icmp_ln15_reg_496 = ap_const_lv1_1) and (icmp_ln879_4_reg_571 = ap_const_lv1_0) and (icmp_ln887_1_reg_547 = ap_const_lv1_0))))) then 
            frequency_V_address0 <= zext_ln49_reg_589(8 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln887_1_reg_547 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln42_reg_575)) or ((icmp_ln879_4_reg_571 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1) and (icmp_ln887_1_reg_547 = ap_const_lv1_0))))) then 
            frequency_V_address0 <= zext_ln44_reg_579(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            frequency_V_address0 <= zext_ln544_5_fu_409_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            frequency_V_address0 <= zext_ln544_fu_348_p1(8 - 1 downto 0);
        else 
            frequency_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    frequency_V_ce0_assign_proc : process(ap_CS_fsm_state2, icmp_ln15_reg_496, ap_CS_fsm_state3, icmp_ln887_1_reg_547, icmp_ln879_4_reg_571, and_ln42_reg_575, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (((ap_const_lv1_1 = and_ln42_reg_575) and (icmp_ln887_1_reg_547 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1)) or ((icmp_ln15_reg_496 = ap_const_lv1_1) and (icmp_ln879_4_reg_571 = ap_const_lv1_0) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)))) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln887_1_reg_547 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln42_reg_575)) or ((icmp_ln879_4_reg_571 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)))))) then 
            frequency_V_ce0 <= ap_const_logic_1;
        else 
            frequency_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frequency_V_d0_assign_proc : process(add_ln209_reg_584, add_ln209_1_reg_594, ap_CS_fsm_state5, ap_condition_222, ap_condition_229)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
            if ((ap_const_boolean_1 = ap_condition_229)) then 
                frequency_V_d0 <= add_ln209_1_reg_594;
            elsif ((ap_const_boolean_1 = ap_condition_222)) then 
                frequency_V_d0 <= add_ln209_reg_584;
            else 
                frequency_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            frequency_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    frequency_V_we0_assign_proc : process(icmp_ln15_reg_496, icmp_ln887_1_reg_547, icmp_ln879_4_reg_571, and_ln42_reg_575, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (((ap_const_lv1_1 = and_ln42_reg_575) and (icmp_ln887_1_reg_547 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1)) or ((icmp_ln15_reg_496 = ap_const_lv1_1) and (icmp_ln879_4_reg_571 = ap_const_lv1_0) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)))) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln887_1_reg_547 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln42_reg_575)) or ((icmp_ln879_4_reg_571 = ap_const_lv1_1) and (icmp_ln15_reg_496 = ap_const_lv1_1) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)))))) then 
            frequency_V_we0 <= ap_const_logic_1;
        else 
            frequency_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_321_p2 <= "1" when (unsigned(frequency_V_q0) < unsigned(in_frequency_V_q0)) else "0";
    i_fu_342_p2 <= std_logic_vector(unsigned(op2_assign_reg_253) + unsigned(ap_const_lv31_1));
    icmp_ln15_fu_337_p2 <= "1" when (signed(zext_ln15_fu_333_p1) < signed(add_ln15_reg_483)) else "0";
    icmp_ln879_2_fu_364_p2 <= "1" when (t_V_3_reg_229 = zext_ln15_reg_488) else "0";
    icmp_ln879_3_fu_425_p2 <= "0" when (t_V_5_reg_266 = zext_ln15_reg_488) else "1";
    icmp_ln879_4_fu_420_p2 <= "1" when (t_V_5_reg_266 = zext_ln15_reg_488) else "0";
    icmp_ln879_fu_369_p2 <= "0" when (t_V_3_reg_229 = zext_ln15_reg_488) else "1";
    icmp_ln887_1_fu_404_p2 <= "1" when (unsigned(ap_phi_mux_t_V_4_phi_fu_280_p4) < unsigned(val_assign_loc_read_reg_477)) else "0";
    icmp_ln887_fu_359_p2 <= "1" when (unsigned(t_V_reg_241) < unsigned(val_assign_loc_read_reg_477)) else "0";
    in_count_V_1_fu_458_p2 <= std_logic_vector(unsigned(t_V_4_reg_277) + unsigned(ap_const_lv32_1));
    in_count_V_fu_385_p2 <= std_logic_vector(unsigned(t_V_reg_241) + unsigned(ap_const_lv32_1));

    in_frequency_V_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln544_3_fu_353_p1, zext_ln544_6_fu_414_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_frequency_V_address0 <= zext_ln544_6_fu_414_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            in_frequency_V_address0 <= zext_ln544_3_fu_353_p1(8 - 1 downto 0);
        else 
            in_frequency_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    in_frequency_V_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            in_frequency_V_ce0 <= ap_const_logic_1;
        else 
            in_frequency_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    in_value_V_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, zext_ln544_3_fu_353_p1, zext_ln544_6_fu_414_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_value_V_address0 <= zext_ln544_6_fu_414_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            in_value_V_address0 <= zext_ln544_3_fu_353_p1(8 - 1 downto 0);
        else 
            in_value_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    in_value_V_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            in_value_V_ce0 <= ap_const_logic_1;
        else 
            in_value_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    left_V_address0_assign_proc : process(ap_CS_fsm_state3, zext_ln28_fu_380_p1, zext_ln33_fu_392_p1, ap_condition_201, ap_condition_208)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((ap_const_boolean_1 = ap_condition_208)) then 
                left_V_address0 <= zext_ln33_fu_392_p1(8 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_201)) then 
                left_V_address0 <= zext_ln28_fu_380_p1(8 - 1 downto 0);
            else 
                left_V_address0 <= "XXXXXXXX";
            end if;
        else 
            left_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    left_V_ce0_assign_proc : process(icmp_ln887_fu_359_p2, ap_CS_fsm_state3, icmp_ln879_2_fu_364_p2, and_ln26_fu_374_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (((ap_const_lv1_1 = and_ln26_fu_374_p2) and (icmp_ln887_fu_359_p2 = ap_const_lv1_1)) or ((icmp_ln879_2_fu_364_p2 = ap_const_lv1_0) and (icmp_ln887_fu_359_p2 = ap_const_lv1_0)))) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln887_fu_359_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln26_fu_374_p2)) or ((icmp_ln879_2_fu_364_p2 = ap_const_lv1_1) and (icmp_ln887_fu_359_p2 = ap_const_lv1_0)))))) then 
            left_V_ce0 <= ap_const_logic_1;
        else 
            left_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    left_V_d0_assign_proc : process(in_value_V_q0, ap_CS_fsm_state3, ap_condition_201, ap_condition_208)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((ap_const_boolean_1 = ap_condition_208)) then 
                left_V_d0 <= ap_const_lv32_FFFFFFFF;
            elsif ((ap_const_boolean_1 = ap_condition_201)) then 
                left_V_d0 <= in_value_V_q0;
            else 
                left_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            left_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    left_V_we0_assign_proc : process(icmp_ln887_fu_359_p2, ap_CS_fsm_state3, icmp_ln879_2_fu_364_p2, and_ln26_fu_374_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (((ap_const_lv1_1 = and_ln26_fu_374_p2) and (icmp_ln887_fu_359_p2 = ap_const_lv1_1)) or ((icmp_ln879_2_fu_364_p2 = ap_const_lv1_0) and (icmp_ln887_fu_359_p2 = ap_const_lv1_0)))) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln887_fu_359_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln26_fu_374_p2)) or ((icmp_ln879_2_fu_364_p2 = ap_const_lv1_1) and (icmp_ln887_fu_359_p2 = ap_const_lv1_0)))))) then 
            left_V_we0 <= ap_const_logic_1;
        else 
            left_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    parent_V_address0_assign_proc : process(zext_ln544_reg_505, ap_CS_fsm_state3, zext_ln544_5_reg_551, ap_CS_fsm_state4, zext_ln544_4_fu_472_p1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            parent_V_address0 <= zext_ln544_4_fu_472_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            parent_V_address0 <= zext_ln544_5_reg_551(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            parent_V_address0 <= zext_ln544_reg_505(8 - 1 downto 0);
        else 
            parent_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    parent_V_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            parent_V_ce0 <= ap_const_logic_1;
        else 
            parent_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    parent_V_d0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, op2_assign_reg_253, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            parent_V_d0 <= ap_const_lv31_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            parent_V_d0 <= op2_assign_reg_253;
        else 
            parent_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    parent_V_we0_assign_proc : process(icmp_ln887_fu_359_p2, ap_CS_fsm_state3, icmp_ln879_2_fu_364_p2, and_ln26_fu_374_p2, icmp_ln887_1_reg_547, icmp_ln879_4_fu_420_p2, ap_CS_fsm_state4, and_ln42_fu_430_p2, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (((ap_const_lv1_1 = and_ln42_fu_430_p2) and (icmp_ln887_1_reg_547 = ap_const_lv1_1)) or ((icmp_ln879_4_fu_420_p2 = ap_const_lv1_0) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)))) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (((ap_const_lv1_1 = and_ln26_fu_374_p2) and (icmp_ln887_fu_359_p2 = ap_const_lv1_1)) or ((icmp_ln879_2_fu_364_p2 = ap_const_lv1_0) and (icmp_ln887_fu_359_p2 = ap_const_lv1_0)))))) then 
            parent_V_we0 <= ap_const_logic_1;
        else 
            parent_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    right_V_address0_assign_proc : process(ap_CS_fsm_state4, zext_ln44_fu_436_p1, zext_ln49_fu_447_p1, ap_condition_156, ap_condition_166)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((ap_const_boolean_1 = ap_condition_166)) then 
                right_V_address0 <= zext_ln49_fu_447_p1(8 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_156)) then 
                right_V_address0 <= zext_ln44_fu_436_p1(8 - 1 downto 0);
            else 
                right_V_address0 <= "XXXXXXXX";
            end if;
        else 
            right_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    right_V_ce0_assign_proc : process(icmp_ln887_1_reg_547, icmp_ln879_4_fu_420_p2, ap_CS_fsm_state4, and_ln42_fu_430_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state4) and (((ap_const_lv1_1 = and_ln42_fu_430_p2) and (icmp_ln887_1_reg_547 = ap_const_lv1_1)) or ((icmp_ln879_4_fu_420_p2 = ap_const_lv1_0) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)))) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (((icmp_ln887_1_reg_547 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln42_fu_430_p2)) or ((icmp_ln879_4_fu_420_p2 = ap_const_lv1_1) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)))))) then 
            right_V_ce0 <= ap_const_logic_1;
        else 
            right_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    right_V_d0_assign_proc : process(in_value_V_q0, ap_CS_fsm_state4, ap_condition_156, ap_condition_166)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((ap_const_boolean_1 = ap_condition_166)) then 
                right_V_d0 <= ap_const_lv32_FFFFFFFF;
            elsif ((ap_const_boolean_1 = ap_condition_156)) then 
                right_V_d0 <= in_value_V_q0;
            else 
                right_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            right_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    right_V_we0_assign_proc : process(icmp_ln887_1_reg_547, icmp_ln879_4_fu_420_p2, ap_CS_fsm_state4, and_ln42_fu_430_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state4) and (((ap_const_lv1_1 = and_ln42_fu_430_p2) and (icmp_ln887_1_reg_547 = ap_const_lv1_1)) or ((icmp_ln879_4_fu_420_p2 = ap_const_lv1_0) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)))) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (((icmp_ln887_1_reg_547 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln42_fu_430_p2)) or ((icmp_ln879_4_fu_420_p2 = ap_const_lv1_1) and (icmp_ln887_1_reg_547 = ap_const_lv1_0)))))) then 
            right_V_we0 <= ap_const_logic_1;
        else 
            right_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tree_count_V_1_fu_465_p2 <= std_logic_vector(unsigned(t_V_5_reg_266) + unsigned(ap_const_lv32_1));
    tree_count_V_fu_397_p2 <= std_logic_vector(unsigned(t_V_3_reg_229) + unsigned(ap_const_lv32_1));

    val_assign_loc_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, val_assign_loc_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            val_assign_loc_blk_n <= val_assign_loc_empty_n;
        else 
            val_assign_loc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    val_assign_loc_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, val_assign_loc_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            val_assign_loc_out_blk_n <= val_assign_loc_out_full_n;
        else 
            val_assign_loc_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    val_assign_loc_out_din <= val_assign_loc_dout;

    val_assign_loc_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, val_assign_loc_empty_n, val_assign_loc_out_full_n)
    begin
        if ((not(((val_assign_loc_out_full_n = ap_const_logic_0) or (val_assign_loc_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            val_assign_loc_out_write <= ap_const_logic_1;
        else 
            val_assign_loc_out_write <= ap_const_logic_0;
        end if; 
    end process;


    val_assign_loc_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, val_assign_loc_empty_n, val_assign_loc_out_full_n)
    begin
        if ((not(((val_assign_loc_out_full_n = ap_const_logic_0) or (val_assign_loc_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            val_assign_loc_read <= ap_const_logic_1;
        else 
            val_assign_loc_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln15_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_assign_reg_253),32));
    zext_ln28_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_assign_reg_253),64));
    zext_ln33_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_assign_reg_253),64));
    zext_ln44_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_assign_reg_253),64));
    zext_ln49_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_assign_reg_253),64));
    zext_ln544_3_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_reg_241),64));
    zext_ln544_4_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_3_reg_229),64));
    zext_ln544_5_fu_409_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_t_V_5_phi_fu_269_p4),64));
    zext_ln544_6_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_t_V_4_phi_fu_280_p4),64));
    zext_ln544_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_3_reg_229),64));
end behav;
