// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "create_tree.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic create_tree::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic create_tree::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> create_tree::ap_ST_fsm_state1 = "1";
const sc_lv<5> create_tree::ap_ST_fsm_state2 = "10";
const sc_lv<5> create_tree::ap_ST_fsm_state3 = "100";
const sc_lv<5> create_tree::ap_ST_fsm_state4 = "1000";
const sc_lv<5> create_tree::ap_ST_fsm_state5 = "10000";
const sc_lv<32> create_tree::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> create_tree::ap_const_lv32_1 = "1";
const sc_lv<1> create_tree::ap_const_lv1_1 = "1";
const sc_lv<32> create_tree::ap_const_lv32_2 = "10";
const sc_lv<32> create_tree::ap_const_lv32_3 = "11";
const sc_lv<1> create_tree::ap_const_lv1_0 = "0";
const sc_lv<32> create_tree::ap_const_lv32_4 = "100";
const sc_lv<31> create_tree::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> create_tree::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<31> create_tree::ap_const_lv31_1 = "1";
const bool create_tree::ap_const_boolean_1 = true;

create_tree::create_tree(sc_module_name name) : sc_module(name), mVcdFile(0) {
    frequency_V_U = new create_tree_frequibs("frequency_V_U");
    frequency_V_U->clk(ap_clk);
    frequency_V_U->reset(ap_rst);
    frequency_V_U->address0(frequency_V_address0);
    frequency_V_U->ce0(frequency_V_ce0);
    frequency_V_U->we0(frequency_V_we0);
    frequency_V_U->d0(frequency_V_d0);
    frequency_V_U->q0(frequency_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln15_fu_290_p2);
    sensitive << ( num_symbols );

    SC_METHOD(thread_add_ln209_1_fu_410_p2);
    sensitive << ( frequency_V_q0 );
    sensitive << ( p_090_0_reg_251 );

    SC_METHOD(thread_add_ln209_fu_404_p2);
    sensitive << ( in_frequency_V_q0 );
    sensitive << ( p_090_0_reg_251 );

    SC_METHOD(thread_and_ln26_fu_342_p2);
    sensitive << ( grp_fu_284_p2 );
    sensitive << ( icmp_ln879_fu_337_p2 );

    SC_METHOD(thread_and_ln42_fu_398_p2);
    sensitive << ( grp_fu_284_p2 );
    sensitive << ( icmp_ln879_3_fu_393_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_condition_169);
    sensitive << ( icmp_ln887_fu_327_p2 );
    sensitive << ( and_ln26_fu_342_p2 );
    sensitive << ( icmp_ln879_2_fu_332_p2 );

    SC_METHOD(thread_ap_condition_176);
    sensitive << ( icmp_ln887_fu_327_p2 );
    sensitive << ( and_ln26_fu_342_p2 );
    sensitive << ( icmp_ln879_2_fu_332_p2 );

    SC_METHOD(thread_ap_condition_188);
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( icmp_ln879_4_reg_537 );
    sensitive << ( and_ln42_reg_541 );

    SC_METHOD(thread_ap_condition_195);
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( icmp_ln879_4_reg_537 );
    sensitive << ( and_ln42_reg_541 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln15_fu_300_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_t_V_3_be_phi_fu_264_p4);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( t_V_5_reg_229 );
    sensitive << ( tree_count_V_1_fu_435_p2 );
    sensitive << ( ap_condition_188 );
    sensitive << ( ap_condition_195 );

    SC_METHOD(thread_ap_phi_mux_t_V_4_phi_fu_243_p4);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( t_V_reg_204 );
    sensitive << ( in_count_V_fu_353_p2 );
    sensitive << ( ap_condition_169 );
    sensitive << ( ap_condition_176 );

    SC_METHOD(thread_ap_phi_mux_t_V_5_phi_fu_232_p4);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( t_V_3_reg_192 );
    sensitive << ( tree_count_V_fu_365_p2 );
    sensitive << ( ap_condition_169 );
    sensitive << ( ap_condition_176 );

    SC_METHOD(thread_ap_phi_mux_t_V_be_phi_fu_276_p4);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( t_V_4_reg_240 );
    sensitive << ( in_count_V_1_fu_422_p2 );
    sensitive << ( ap_condition_188 );
    sensitive << ( ap_condition_195 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln15_fu_300_p2 );

    SC_METHOD(thread_frequency_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln544_5_fu_311_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( zext_ln544_7_fu_377_p1 );
    sensitive << ( icmp_ln879_4_reg_537 );
    sensitive << ( and_ln42_reg_541 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln44_fu_416_p1 );
    sensitive << ( zext_ln49_fu_429_p1 );

    SC_METHOD(thread_frequency_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( icmp_ln879_4_reg_537 );
    sensitive << ( and_ln42_reg_541 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_frequency_V_d0);
    sensitive << ( add_ln209_reg_545 );
    sensitive << ( add_ln209_1_reg_550 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_condition_188 );
    sensitive << ( ap_condition_195 );

    SC_METHOD(thread_frequency_V_we0);
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( icmp_ln879_4_reg_537 );
    sensitive << ( and_ln42_reg_541 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_fu_284_p2);
    sensitive << ( in_frequency_V_q0 );
    sensitive << ( frequency_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln887_fu_327_p2 );

    SC_METHOD(thread_i_fu_305_p2);
    sensitive << ( op2_assign_reg_216 );

    SC_METHOD(thread_icmp_ln15_fu_300_p2);
    sensitive << ( add_ln15_reg_448 );
    sensitive << ( zext_ln15_fu_296_p1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_icmp_ln879_2_fu_332_p2);
    sensitive << ( zext_ln15_reg_453 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( t_V_3_reg_192 );
    sensitive << ( icmp_ln887_fu_327_p2 );

    SC_METHOD(thread_icmp_ln879_3_fu_393_p2);
    sensitive << ( zext_ln15_reg_453 );
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( t_V_5_reg_229 );

    SC_METHOD(thread_icmp_ln879_4_fu_388_p2);
    sensitive << ( zext_ln15_reg_453 );
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( t_V_5_reg_229 );

    SC_METHOD(thread_icmp_ln879_fu_337_p2);
    sensitive << ( zext_ln15_reg_453 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( t_V_3_reg_192 );
    sensitive << ( icmp_ln887_fu_327_p2 );

    SC_METHOD(thread_icmp_ln887_1_fu_372_p2);
    sensitive << ( num_symbols );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_phi_mux_t_V_4_phi_fu_243_p4 );

    SC_METHOD(thread_icmp_ln887_fu_327_p2);
    sensitive << ( num_symbols );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( t_V_reg_204 );

    SC_METHOD(thread_in_count_V_1_fu_422_p2);
    sensitive << ( t_V_4_reg_240 );

    SC_METHOD(thread_in_count_V_fu_353_p2);
    sensitive << ( t_V_reg_204 );

    SC_METHOD(thread_in_frequency_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln544_6_fu_316_p1 );
    sensitive << ( zext_ln544_8_fu_382_p1 );

    SC_METHOD(thread_in_frequency_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in_value_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln544_6_fu_316_p1 );
    sensitive << ( zext_ln544_8_fu_382_p1 );

    SC_METHOD(thread_in_value_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_left_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln28_fu_348_p1 );
    sensitive << ( zext_ln33_fu_360_p1 );
    sensitive << ( ap_condition_169 );
    sensitive << ( ap_condition_176 );

    SC_METHOD(thread_left_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln887_fu_327_p2 );
    sensitive << ( and_ln26_fu_342_p2 );
    sensitive << ( icmp_ln879_2_fu_332_p2 );

    SC_METHOD(thread_left_V_d0);
    sensitive << ( in_value_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_condition_169 );
    sensitive << ( ap_condition_176 );

    SC_METHOD(thread_left_V_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln887_fu_327_p2 );
    sensitive << ( and_ln26_fu_342_p2 );
    sensitive << ( icmp_ln879_2_fu_332_p2 );

    SC_METHOD(thread_parent_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln544_5_reg_469 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln544_7_reg_512 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln544_fu_322_p1 );

    SC_METHOD(thread_parent_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_parent_V_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( op2_assign_reg_216 );

    SC_METHOD(thread_parent_V_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln15_fu_300_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln879_4_fu_388_p2 );
    sensitive << ( and_ln42_fu_398_p2 );
    sensitive << ( icmp_ln887_fu_327_p2 );
    sensitive << ( and_ln26_fu_342_p2 );
    sensitive << ( icmp_ln879_2_fu_332_p2 );

    SC_METHOD(thread_right_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln44_fu_416_p1 );
    sensitive << ( zext_ln49_fu_429_p1 );
    sensitive << ( ap_condition_188 );
    sensitive << ( ap_condition_195 );

    SC_METHOD(thread_right_V_ce0);
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( icmp_ln879_4_reg_537 );
    sensitive << ( and_ln42_reg_541 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_right_V_d0);
    sensitive << ( in_value_V_load_1_reg_532 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_condition_188 );
    sensitive << ( ap_condition_195 );

    SC_METHOD(thread_right_V_we0);
    sensitive << ( icmp_ln887_1_reg_508 );
    sensitive << ( icmp_ln879_4_reg_537 );
    sensitive << ( and_ln42_reg_541 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_tree_count_V_1_fu_435_p2);
    sensitive << ( t_V_5_reg_229 );

    SC_METHOD(thread_tree_count_V_fu_365_p2);
    sensitive << ( t_V_3_reg_192 );

    SC_METHOD(thread_zext_ln15_fu_296_p1);
    sensitive << ( op2_assign_reg_216 );

    SC_METHOD(thread_zext_ln28_fu_348_p1);
    sensitive << ( op2_assign_reg_216 );

    SC_METHOD(thread_zext_ln33_fu_360_p1);
    sensitive << ( op2_assign_reg_216 );

    SC_METHOD(thread_zext_ln44_fu_416_p1);
    sensitive << ( op2_assign_reg_216 );

    SC_METHOD(thread_zext_ln49_fu_429_p1);
    sensitive << ( op2_assign_reg_216 );

    SC_METHOD(thread_zext_ln544_5_fu_311_p1);
    sensitive << ( t_V_3_reg_192 );

    SC_METHOD(thread_zext_ln544_6_fu_316_p1);
    sensitive << ( t_V_reg_204 );

    SC_METHOD(thread_zext_ln544_7_fu_377_p1);
    sensitive << ( ap_phi_mux_t_V_5_phi_fu_232_p4 );

    SC_METHOD(thread_zext_ln544_8_fu_382_p1);
    sensitive << ( ap_phi_mux_t_V_4_phi_fu_243_p4 );

    SC_METHOD(thread_zext_ln544_fu_322_p1);
    sensitive << ( t_V_3_reg_192 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln15_fu_300_p2 );

    ap_CS_fsm = "00001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "create_tree_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_value_V_address0, "(port)in_value_V_address0");
    sc_trace(mVcdFile, in_value_V_ce0, "(port)in_value_V_ce0");
    sc_trace(mVcdFile, in_value_V_q0, "(port)in_value_V_q0");
    sc_trace(mVcdFile, in_frequency_V_address0, "(port)in_frequency_V_address0");
    sc_trace(mVcdFile, in_frequency_V_ce0, "(port)in_frequency_V_ce0");
    sc_trace(mVcdFile, in_frequency_V_q0, "(port)in_frequency_V_q0");
    sc_trace(mVcdFile, num_symbols, "(port)num_symbols");
    sc_trace(mVcdFile, parent_V_address0, "(port)parent_V_address0");
    sc_trace(mVcdFile, parent_V_ce0, "(port)parent_V_ce0");
    sc_trace(mVcdFile, parent_V_we0, "(port)parent_V_we0");
    sc_trace(mVcdFile, parent_V_d0, "(port)parent_V_d0");
    sc_trace(mVcdFile, left_V_address0, "(port)left_V_address0");
    sc_trace(mVcdFile, left_V_ce0, "(port)left_V_ce0");
    sc_trace(mVcdFile, left_V_we0, "(port)left_V_we0");
    sc_trace(mVcdFile, left_V_d0, "(port)left_V_d0");
    sc_trace(mVcdFile, right_V_address0, "(port)right_V_address0");
    sc_trace(mVcdFile, right_V_ce0, "(port)right_V_ce0");
    sc_trace(mVcdFile, right_V_we0, "(port)right_V_we0");
    sc_trace(mVcdFile, right_V_d0, "(port)right_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, add_ln15_fu_290_p2, "add_ln15_fu_290_p2");
    sc_trace(mVcdFile, add_ln15_reg_448, "add_ln15_reg_448");
    sc_trace(mVcdFile, zext_ln15_fu_296_p1, "zext_ln15_fu_296_p1");
    sc_trace(mVcdFile, zext_ln15_reg_453, "zext_ln15_reg_453");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_305_p2, "i_fu_305_p2");
    sc_trace(mVcdFile, i_reg_464, "i_reg_464");
    sc_trace(mVcdFile, zext_ln544_5_fu_311_p1, "zext_ln544_5_fu_311_p1");
    sc_trace(mVcdFile, zext_ln544_5_reg_469, "zext_ln544_5_reg_469");
    sc_trace(mVcdFile, icmp_ln15_fu_300_p2, "icmp_ln15_fu_300_p2");
    sc_trace(mVcdFile, frequency_V_q0, "frequency_V_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln887_1_fu_372_p2, "icmp_ln887_1_fu_372_p2");
    sc_trace(mVcdFile, icmp_ln887_1_reg_508, "icmp_ln887_1_reg_508");
    sc_trace(mVcdFile, zext_ln544_7_fu_377_p1, "zext_ln544_7_fu_377_p1");
    sc_trace(mVcdFile, zext_ln544_7_reg_512, "zext_ln544_7_reg_512");
    sc_trace(mVcdFile, in_value_V_load_1_reg_532, "in_value_V_load_1_reg_532");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln879_4_fu_388_p2, "icmp_ln879_4_fu_388_p2");
    sc_trace(mVcdFile, icmp_ln879_4_reg_537, "icmp_ln879_4_reg_537");
    sc_trace(mVcdFile, and_ln42_fu_398_p2, "and_ln42_fu_398_p2");
    sc_trace(mVcdFile, and_ln42_reg_541, "and_ln42_reg_541");
    sc_trace(mVcdFile, add_ln209_fu_404_p2, "add_ln209_fu_404_p2");
    sc_trace(mVcdFile, add_ln209_reg_545, "add_ln209_reg_545");
    sc_trace(mVcdFile, add_ln209_1_fu_410_p2, "add_ln209_1_fu_410_p2");
    sc_trace(mVcdFile, add_ln209_1_reg_550, "add_ln209_1_reg_550");
    sc_trace(mVcdFile, frequency_V_address0, "frequency_V_address0");
    sc_trace(mVcdFile, frequency_V_ce0, "frequency_V_ce0");
    sc_trace(mVcdFile, frequency_V_we0, "frequency_V_we0");
    sc_trace(mVcdFile, frequency_V_d0, "frequency_V_d0");
    sc_trace(mVcdFile, t_V_3_reg_192, "t_V_3_reg_192");
    sc_trace(mVcdFile, ap_phi_mux_t_V_3_be_phi_fu_264_p4, "ap_phi_mux_t_V_3_be_phi_fu_264_p4");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, t_V_reg_204, "t_V_reg_204");
    sc_trace(mVcdFile, ap_phi_mux_t_V_be_phi_fu_276_p4, "ap_phi_mux_t_V_be_phi_fu_276_p4");
    sc_trace(mVcdFile, op2_assign_reg_216, "op2_assign_reg_216");
    sc_trace(mVcdFile, ap_phi_mux_t_V_5_phi_fu_232_p4, "ap_phi_mux_t_V_5_phi_fu_232_p4");
    sc_trace(mVcdFile, t_V_5_reg_229, "t_V_5_reg_229");
    sc_trace(mVcdFile, icmp_ln887_fu_327_p2, "icmp_ln887_fu_327_p2");
    sc_trace(mVcdFile, and_ln26_fu_342_p2, "and_ln26_fu_342_p2");
    sc_trace(mVcdFile, icmp_ln879_2_fu_332_p2, "icmp_ln879_2_fu_332_p2");
    sc_trace(mVcdFile, tree_count_V_fu_365_p2, "tree_count_V_fu_365_p2");
    sc_trace(mVcdFile, in_count_V_fu_353_p2, "in_count_V_fu_353_p2");
    sc_trace(mVcdFile, ap_phi_mux_t_V_4_phi_fu_243_p4, "ap_phi_mux_t_V_4_phi_fu_243_p4");
    sc_trace(mVcdFile, t_V_4_reg_240, "t_V_4_reg_240");
    sc_trace(mVcdFile, p_090_0_reg_251, "p_090_0_reg_251");
    sc_trace(mVcdFile, tree_count_V_1_fu_435_p2, "tree_count_V_1_fu_435_p2");
    sc_trace(mVcdFile, in_count_V_1_fu_422_p2, "in_count_V_1_fu_422_p2");
    sc_trace(mVcdFile, zext_ln544_6_fu_316_p1, "zext_ln544_6_fu_316_p1");
    sc_trace(mVcdFile, zext_ln544_fu_322_p1, "zext_ln544_fu_322_p1");
    sc_trace(mVcdFile, zext_ln28_fu_348_p1, "zext_ln28_fu_348_p1");
    sc_trace(mVcdFile, zext_ln33_fu_360_p1, "zext_ln33_fu_360_p1");
    sc_trace(mVcdFile, zext_ln544_8_fu_382_p1, "zext_ln544_8_fu_382_p1");
    sc_trace(mVcdFile, zext_ln44_fu_416_p1, "zext_ln44_fu_416_p1");
    sc_trace(mVcdFile, zext_ln49_fu_429_p1, "zext_ln49_fu_429_p1");
    sc_trace(mVcdFile, grp_fu_284_p2, "grp_fu_284_p2");
    sc_trace(mVcdFile, icmp_ln879_fu_337_p2, "icmp_ln879_fu_337_p2");
    sc_trace(mVcdFile, icmp_ln879_3_fu_393_p2, "icmp_ln879_3_fu_393_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_188, "ap_condition_188");
    sc_trace(mVcdFile, ap_condition_195, "ap_condition_195");
    sc_trace(mVcdFile, ap_condition_169, "ap_condition_169");
    sc_trace(mVcdFile, ap_condition_176, "ap_condition_176");
#endif

    }
}

create_tree::~create_tree() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete frequency_V_U;
}

void create_tree::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        op2_assign_reg_216 = i_reg_464.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        op2_assign_reg_216 = ap_const_lv31_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if (esl_seteq<1,1,1>(ap_condition_176.read(), ap_const_boolean_1)) {
            p_090_0_reg_251 = frequency_V_q0.read();
        } else if (esl_seteq<1,1,1>(ap_condition_169.read(), ap_const_boolean_1)) {
            p_090_0_reg_251 = in_frequency_V_q0.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        t_V_3_reg_192 = ap_phi_mux_t_V_3_be_phi_fu_264_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        t_V_3_reg_192 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if (esl_seteq<1,1,1>(ap_condition_176.read(), ap_const_boolean_1)) {
            t_V_4_reg_240 = t_V_reg_204.read();
        } else if (esl_seteq<1,1,1>(ap_condition_169.read(), ap_const_boolean_1)) {
            t_V_4_reg_240 = in_count_V_fu_353_p2.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if (esl_seteq<1,1,1>(ap_condition_176.read(), ap_const_boolean_1)) {
            t_V_5_reg_229 = tree_count_V_fu_365_p2.read();
        } else if (esl_seteq<1,1,1>(ap_condition_169.read(), ap_const_boolean_1)) {
            t_V_5_reg_229 = t_V_3_reg_192.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        t_V_reg_204 = ap_phi_mux_t_V_be_phi_fu_276_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        t_V_reg_204 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        add_ln15_reg_448 = add_ln15_fu_290_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, and_ln42_fu_398_p2.read())) || 
  (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(icmp_ln879_4_fu_388_p2.read(), ap_const_lv1_0))))) {
        add_ln209_1_reg_550 = add_ln209_1_fu_410_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, and_ln42_fu_398_p2.read())) || 
  (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln879_4_fu_388_p2.read()))))) {
        add_ln209_reg_545 = add_ln209_fu_404_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()))) {
        and_ln42_reg_541 = and_ln42_fu_398_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_464 = i_fu_305_p2.read();
        zext_ln15_reg_453 = zext_ln15_fu_296_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0))) {
        icmp_ln879_4_reg_537 = icmp_ln879_4_fu_388_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        icmp_ln887_1_reg_508 = icmp_ln887_1_fu_372_p2.read();
        zext_ln544_7_reg_512 = zext_ln544_7_fu_377_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        in_value_V_load_1_reg_532 = in_value_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_300_p2.read(), ap_const_lv1_1))) {
        zext_ln544_5_reg_469 = zext_ln544_5_fu_311_p1.read();
    }
}

void create_tree::thread_add_ln15_fu_290_p2() {
    add_ln15_fu_290_p2 = (!num_symbols.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(num_symbols.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void create_tree::thread_add_ln209_1_fu_410_p2() {
    add_ln209_1_fu_410_p2 = (!frequency_V_q0.read().is_01() || !p_090_0_reg_251.read().is_01())? sc_lv<32>(): (sc_biguint<32>(frequency_V_q0.read()) + sc_biguint<32>(p_090_0_reg_251.read()));
}

void create_tree::thread_add_ln209_fu_404_p2() {
    add_ln209_fu_404_p2 = (!in_frequency_V_q0.read().is_01() || !p_090_0_reg_251.read().is_01())? sc_lv<32>(): (sc_biguint<32>(in_frequency_V_q0.read()) + sc_biguint<32>(p_090_0_reg_251.read()));
}

void create_tree::thread_and_ln26_fu_342_p2() {
    and_ln26_fu_342_p2 = (grp_fu_284_p2.read() & icmp_ln879_fu_337_p2.read());
}

void create_tree::thread_and_ln42_fu_398_p2() {
    and_ln42_fu_398_p2 = (grp_fu_284_p2.read() & icmp_ln879_3_fu_393_p2.read());
}

void create_tree::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void create_tree::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void create_tree::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void create_tree::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void create_tree::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void create_tree::thread_ap_condition_169() {
    ap_condition_169 = ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_327_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln26_fu_342_p2.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_fu_327_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln879_2_fu_332_p2.read())));
}

void create_tree::thread_ap_condition_176() {
    ap_condition_176 = ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_327_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, and_ln26_fu_342_p2.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_fu_327_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln879_2_fu_332_p2.read())));
}

void create_tree::thread_ap_condition_188() {
    ap_condition_188 = ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln42_reg_541.read())) || (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln879_4_reg_537.read())));
}

void create_tree::thread_ap_condition_195() {
    ap_condition_195 = ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, and_ln42_reg_541.read())) || (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(icmp_ln879_4_reg_537.read(), ap_const_lv1_0)));
}

void create_tree::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln15_fu_300_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void create_tree::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void create_tree::thread_ap_phi_mux_t_V_3_be_phi_fu_264_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        if (esl_seteq<1,1,1>(ap_condition_195.read(), ap_const_boolean_1)) {
            ap_phi_mux_t_V_3_be_phi_fu_264_p4 = tree_count_V_1_fu_435_p2.read();
        } else if (esl_seteq<1,1,1>(ap_condition_188.read(), ap_const_boolean_1)) {
            ap_phi_mux_t_V_3_be_phi_fu_264_p4 = t_V_5_reg_229.read();
        } else {
            ap_phi_mux_t_V_3_be_phi_fu_264_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_t_V_3_be_phi_fu_264_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void create_tree::thread_ap_phi_mux_t_V_4_phi_fu_243_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if (esl_seteq<1,1,1>(ap_condition_176.read(), ap_const_boolean_1)) {
            ap_phi_mux_t_V_4_phi_fu_243_p4 = t_V_reg_204.read();
        } else if (esl_seteq<1,1,1>(ap_condition_169.read(), ap_const_boolean_1)) {
            ap_phi_mux_t_V_4_phi_fu_243_p4 = in_count_V_fu_353_p2.read();
        } else {
            ap_phi_mux_t_V_4_phi_fu_243_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_t_V_4_phi_fu_243_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void create_tree::thread_ap_phi_mux_t_V_5_phi_fu_232_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if (esl_seteq<1,1,1>(ap_condition_176.read(), ap_const_boolean_1)) {
            ap_phi_mux_t_V_5_phi_fu_232_p4 = tree_count_V_fu_365_p2.read();
        } else if (esl_seteq<1,1,1>(ap_condition_169.read(), ap_const_boolean_1)) {
            ap_phi_mux_t_V_5_phi_fu_232_p4 = t_V_3_reg_192.read();
        } else {
            ap_phi_mux_t_V_5_phi_fu_232_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_t_V_5_phi_fu_232_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void create_tree::thread_ap_phi_mux_t_V_be_phi_fu_276_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        if (esl_seteq<1,1,1>(ap_condition_195.read(), ap_const_boolean_1)) {
            ap_phi_mux_t_V_be_phi_fu_276_p4 = t_V_4_reg_240.read();
        } else if (esl_seteq<1,1,1>(ap_condition_188.read(), ap_const_boolean_1)) {
            ap_phi_mux_t_V_be_phi_fu_276_p4 = in_count_V_1_fu_422_p2.read();
        } else {
            ap_phi_mux_t_V_be_phi_fu_276_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_t_V_be_phi_fu_276_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void create_tree::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln15_fu_300_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void create_tree::thread_frequency_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, and_ln42_reg_541.read())) || 
          (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(icmp_ln879_4_reg_537.read(), ap_const_lv1_0))))) {
        frequency_V_address0 =  (sc_lv<8>) (zext_ln49_fu_429_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
                  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln42_reg_541.read())) || 
                 (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
                  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln879_4_reg_537.read()))))) {
        frequency_V_address0 =  (sc_lv<8>) (zext_ln44_fu_416_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        frequency_V_address0 =  (sc_lv<8>) (zext_ln544_7_fu_377_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        frequency_V_address0 =  (sc_lv<8>) (zext_ln544_5_fu_311_p1.read());
    } else {
        frequency_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void create_tree::thread_frequency_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, and_ln42_reg_541.read())) || 
           (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln879_4_reg_537.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, and_ln42_reg_541.read())) || 
           (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(icmp_ln879_4_reg_537.read(), ap_const_lv1_0)))))) {
        frequency_V_ce0 = ap_const_logic_1;
    } else {
        frequency_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_frequency_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        if (esl_seteq<1,1,1>(ap_condition_195.read(), ap_const_boolean_1)) {
            frequency_V_d0 = add_ln209_1_reg_550.read();
        } else if (esl_seteq<1,1,1>(ap_condition_188.read(), ap_const_boolean_1)) {
            frequency_V_d0 = add_ln209_reg_545.read();
        } else {
            frequency_V_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        frequency_V_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void create_tree::thread_frequency_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, and_ln42_reg_541.read())) || 
           (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln879_4_reg_537.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, and_ln42_reg_541.read())) || 
           (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(icmp_ln879_4_reg_537.read(), ap_const_lv1_0)))))) {
        frequency_V_we0 = ap_const_logic_1;
    } else {
        frequency_V_we0 = ap_const_logic_0;
    }
}

void create_tree::thread_grp_fu_284_p2() {
    grp_fu_284_p2 = (!frequency_V_q0.read().is_01() || !in_frequency_V_q0.read().is_01())? sc_lv<1>(): (sc_biguint<32>(frequency_V_q0.read()) < sc_biguint<32>(in_frequency_V_q0.read()));
}

void create_tree::thread_i_fu_305_p2() {
    i_fu_305_p2 = (!op2_assign_reg_216.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(op2_assign_reg_216.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void create_tree::thread_icmp_ln15_fu_300_p2() {
    icmp_ln15_fu_300_p2 = (!zext_ln15_fu_296_p1.read().is_01() || !add_ln15_reg_448.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln15_fu_296_p1.read()) < sc_bigint<32>(add_ln15_reg_448.read()));
}

void create_tree::thread_icmp_ln879_2_fu_332_p2() {
    icmp_ln879_2_fu_332_p2 = (!t_V_3_reg_192.read().is_01() || !zext_ln15_reg_453.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_3_reg_192.read() == zext_ln15_reg_453.read());
}

void create_tree::thread_icmp_ln879_3_fu_393_p2() {
    icmp_ln879_3_fu_393_p2 = (!t_V_5_reg_229.read().is_01() || !zext_ln15_reg_453.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_5_reg_229.read() != zext_ln15_reg_453.read());
}

void create_tree::thread_icmp_ln879_4_fu_388_p2() {
    icmp_ln879_4_fu_388_p2 = (!t_V_5_reg_229.read().is_01() || !zext_ln15_reg_453.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_5_reg_229.read() == zext_ln15_reg_453.read());
}

void create_tree::thread_icmp_ln879_fu_337_p2() {
    icmp_ln879_fu_337_p2 = (!t_V_3_reg_192.read().is_01() || !zext_ln15_reg_453.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_3_reg_192.read() != zext_ln15_reg_453.read());
}

void create_tree::thread_icmp_ln887_1_fu_372_p2() {
    icmp_ln887_1_fu_372_p2 = (!ap_phi_mux_t_V_4_phi_fu_243_p4.read().is_01() || !num_symbols.read().is_01())? sc_lv<1>(): (sc_biguint<32>(ap_phi_mux_t_V_4_phi_fu_243_p4.read()) < sc_biguint<32>(num_symbols.read()));
}

void create_tree::thread_icmp_ln887_fu_327_p2() {
    icmp_ln887_fu_327_p2 = (!t_V_reg_204.read().is_01() || !num_symbols.read().is_01())? sc_lv<1>(): (sc_biguint<32>(t_V_reg_204.read()) < sc_biguint<32>(num_symbols.read()));
}

void create_tree::thread_in_count_V_1_fu_422_p2() {
    in_count_V_1_fu_422_p2 = (!t_V_4_reg_240.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_4_reg_240.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void create_tree::thread_in_count_V_fu_353_p2() {
    in_count_V_fu_353_p2 = (!t_V_reg_204.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_reg_204.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void create_tree::thread_in_frequency_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in_frequency_V_address0 =  (sc_lv<8>) (zext_ln544_8_fu_382_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        in_frequency_V_address0 =  (sc_lv<8>) (zext_ln544_6_fu_316_p1.read());
    } else {
        in_frequency_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void create_tree::thread_in_frequency_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        in_frequency_V_ce0 = ap_const_logic_1;
    } else {
        in_frequency_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_in_value_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in_value_V_address0 =  (sc_lv<8>) (zext_ln544_8_fu_382_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        in_value_V_address0 =  (sc_lv<8>) (zext_ln544_6_fu_316_p1.read());
    } else {
        in_value_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void create_tree::thread_in_value_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        in_value_V_ce0 = ap_const_logic_1;
    } else {
        in_value_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_left_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if (esl_seteq<1,1,1>(ap_condition_176.read(), ap_const_boolean_1)) {
            left_V_address0 =  (sc_lv<8>) (zext_ln33_fu_360_p1.read());
        } else if (esl_seteq<1,1,1>(ap_condition_169.read(), ap_const_boolean_1)) {
            left_V_address0 =  (sc_lv<8>) (zext_ln28_fu_348_p1.read());
        } else {
            left_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
        }
    } else {
        left_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void create_tree::thread_left_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_327_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, and_ln26_fu_342_p2.read())) || 
           (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_fu_327_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln879_2_fu_332_p2.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_327_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, and_ln26_fu_342_p2.read())) || 
           (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_fu_327_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln879_2_fu_332_p2.read())))))) {
        left_V_ce0 = ap_const_logic_1;
    } else {
        left_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_left_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if (esl_seteq<1,1,1>(ap_condition_176.read(), ap_const_boolean_1)) {
            left_V_d0 = ap_const_lv32_FFFFFFFF;
        } else if (esl_seteq<1,1,1>(ap_condition_169.read(), ap_const_boolean_1)) {
            left_V_d0 = in_value_V_q0.read();
        } else {
            left_V_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        left_V_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void create_tree::thread_left_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_327_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, and_ln26_fu_342_p2.read())) || 
           (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_fu_327_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln879_2_fu_332_p2.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_327_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, and_ln26_fu_342_p2.read())) || 
           (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_fu_327_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln879_2_fu_332_p2.read())))))) {
        left_V_we0 = ap_const_logic_1;
    } else {
        left_V_we0 = ap_const_logic_0;
    }
}

void create_tree::thread_parent_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        parent_V_address0 =  (sc_lv<8>) (zext_ln544_7_reg_512.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        parent_V_address0 =  (sc_lv<8>) (zext_ln544_5_reg_469.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        parent_V_address0 =  (sc_lv<8>) (zext_ln544_fu_322_p1.read());
    } else {
        parent_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void create_tree::thread_parent_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        parent_V_ce0 = ap_const_logic_1;
    } else {
        parent_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_parent_V_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        parent_V_d0 = op2_assign_reg_216.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        parent_V_d0 = ap_const_lv31_0;
    } else {
        parent_V_d0 =  (sc_lv<31>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void create_tree::thread_parent_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, and_ln42_fu_398_p2.read())) || 
           (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(icmp_ln879_4_fu_388_p2.read(), ap_const_lv1_0)))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_327_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, and_ln26_fu_342_p2.read())) || 
           (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_fu_327_p2.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln879_2_fu_332_p2.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln15_fu_300_p2.read(), ap_const_lv1_0)))) {
        parent_V_we0 = ap_const_logic_1;
    } else {
        parent_V_we0 = ap_const_logic_0;
    }
}

void create_tree::thread_right_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        if (esl_seteq<1,1,1>(ap_condition_195.read(), ap_const_boolean_1)) {
            right_V_address0 =  (sc_lv<8>) (zext_ln49_fu_429_p1.read());
        } else if (esl_seteq<1,1,1>(ap_condition_188.read(), ap_const_boolean_1)) {
            right_V_address0 =  (sc_lv<8>) (zext_ln44_fu_416_p1.read());
        } else {
            right_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
        }
    } else {
        right_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void create_tree::thread_right_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, and_ln42_reg_541.read())) || 
           (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln879_4_reg_537.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, and_ln42_reg_541.read())) || 
           (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(icmp_ln879_4_reg_537.read(), ap_const_lv1_0)))))) {
        right_V_ce0 = ap_const_logic_1;
    } else {
        right_V_ce0 = ap_const_logic_0;
    }
}

void create_tree::thread_right_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        if (esl_seteq<1,1,1>(ap_condition_195.read(), ap_const_boolean_1)) {
            right_V_d0 = ap_const_lv32_FFFFFFFF;
        } else if (esl_seteq<1,1,1>(ap_condition_188.read(), ap_const_boolean_1)) {
            right_V_d0 = in_value_V_load_1_reg_532.read();
        } else {
            right_V_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        right_V_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void create_tree::thread_right_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_0, and_ln42_reg_541.read())) || 
           (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln879_4_reg_537.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_reg_508.read()) && 
            esl_seteq<1,1,1>(ap_const_lv1_1, and_ln42_reg_541.read())) || 
           (esl_seteq<1,1,1>(icmp_ln887_1_reg_508.read(), ap_const_lv1_0) && 
            esl_seteq<1,1,1>(icmp_ln879_4_reg_537.read(), ap_const_lv1_0)))))) {
        right_V_we0 = ap_const_logic_1;
    } else {
        right_V_we0 = ap_const_logic_0;
    }
}

void create_tree::thread_tree_count_V_1_fu_435_p2() {
    tree_count_V_1_fu_435_p2 = (!t_V_5_reg_229.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_5_reg_229.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void create_tree::thread_tree_count_V_fu_365_p2() {
    tree_count_V_fu_365_p2 = (!t_V_3_reg_192.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_3_reg_192.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void create_tree::thread_zext_ln15_fu_296_p1() {
    zext_ln15_fu_296_p1 = esl_zext<32,31>(op2_assign_reg_216.read());
}

void create_tree::thread_zext_ln28_fu_348_p1() {
    zext_ln28_fu_348_p1 = esl_zext<64,31>(op2_assign_reg_216.read());
}

void create_tree::thread_zext_ln33_fu_360_p1() {
    zext_ln33_fu_360_p1 = esl_zext<64,31>(op2_assign_reg_216.read());
}

void create_tree::thread_zext_ln44_fu_416_p1() {
    zext_ln44_fu_416_p1 = esl_zext<64,31>(op2_assign_reg_216.read());
}

void create_tree::thread_zext_ln49_fu_429_p1() {
    zext_ln49_fu_429_p1 = esl_zext<64,31>(op2_assign_reg_216.read());
}

void create_tree::thread_zext_ln544_5_fu_311_p1() {
    zext_ln544_5_fu_311_p1 = esl_zext<64,32>(t_V_3_reg_192.read());
}

void create_tree::thread_zext_ln544_6_fu_316_p1() {
    zext_ln544_6_fu_316_p1 = esl_zext<64,32>(t_V_reg_204.read());
}

void create_tree::thread_zext_ln544_7_fu_377_p1() {
    zext_ln544_7_fu_377_p1 = esl_zext<64,32>(ap_phi_mux_t_V_5_phi_fu_232_p4.read());
}

void create_tree::thread_zext_ln544_8_fu_382_p1() {
    zext_ln544_8_fu_382_p1 = esl_zext<64,32>(ap_phi_mux_t_V_4_phi_fu_243_p4.read());
}

void create_tree::thread_zext_ln544_fu_322_p1() {
    zext_ln544_fu_322_p1 = esl_zext<64,32>(t_V_3_reg_192.read());
}

void create_tree::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_300_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

